# Generated by Django 5.2.1 on 2025-06-01 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customer_email_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['origin_type', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='origin_type',
            field=models.CharField(choices=[('local', 'Barang Lokal'), ('foreign', 'Barang Asing')], default='local', help_text='Pilih apakah kategori ini untuk barang lokal atau asing', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Kategori induk (opsional untuk subkategori)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'origin_type', 'parent')},
        ),
    ]
