# Generated by Django 5.2.1 on 2025-06-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options_category_origin_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_channel',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, default='cod', max_length=20),
        ),
    ]
