services:
  - type: web
    name: mengtumbas
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn mengtumbas_store.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: mengtumbas_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: mengtumbas.onrender.com,localhost,127.0.0.1
      - key: PORT
        value: 10000

databases:
  - name: mengtumbas_db
    plan: free
