services:
  - type: web
    name: mengtumbas
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn mengtumbas_store.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_DEBUG
        value: False
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: mengtumbas.onrender.com
      - key: PORT
        value: 10000
